site_name: Finanza Personale

markdown_extensions:
  - mdx_truly_sane_lists  # allow 2 space indent
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang: 
        - it
        - en
  - awesome-pages
  - ezlinks

theme:
  name: material
  language: it
  palette:
    primary: green
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - search.highlight
